/**
 * Item database for the travel checklist generator.
 * Each item has conditions that determine when it should appear.
 *
 * Conditions (all optional, AND logic):
 *   destination: ['domestic'] | ['international'] | ['domestic','international']
 *   season: ['spring','summer','fall','winter'] (any match)
 *   transport: ['plane','train','car'] (any match)
 *   tripType: ['business','leisure','adventure','beach'] (any match)
 *   minDays: number  — include when duration >= minDays
 *   maxDays: number  — include when duration <= maxDays
 *
 * Priority: 'critical' | 'high' | 'medium' | 'low'
 */

export const CATEGORIES = [
  'documents',
  'clothing',
  'toiletries',
  'electronics',
  'health',
  'entertainment',
  'misc',
];

export const ITEMS = [
  // ─── Documents ─────────────────────────────────────────────────────────────
  {
    id: 'passport',
    category: 'documents',
    name: { ja: 'パスポート', en: 'Passport' },
    conditions: { destination: ['international'] },
    priority: 'critical',
  },
  {
    id: 'visa',
    category: 'documents',
    name: { ja: 'ビザ確認', en: 'Visa check' },
    conditions: { destination: ['international'] },
    priority: 'critical',
  },
  {
    id: 'id-card',
    category: 'documents',
    name: { ja: '身分証明書', en: 'ID card' },
    conditions: {},
    priority: 'critical',
  },
  {
    id: 'boarding-pass',
    category: 'documents',
    name: { ja: '搭乗券', en: 'Boarding pass' },
    conditions: { transport: ['plane'] },
    priority: 'critical',
  },
  {
    id: 'train-ticket',
    category: 'documents',
    name: { ja: '乗車券・予約確認', en: 'Train ticket / reservation' },
    conditions: { transport: ['train'] },
    priority: 'critical',
  },
  {
    id: 'travel-insurance',
    category: 'documents',
    name: { ja: '海外旅行保険証', en: 'Travel insurance card' },
    conditions: { destination: ['international'] },
    priority: 'high',
  },
  {
    id: 'hotel-confirmation',
    category: 'documents',
    name: { ja: 'ホテル予約確認書', en: 'Hotel confirmation' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'business-cards',
    category: 'documents',
    name: { ja: '名刺', en: 'Business cards' },
    conditions: { tripType: ['business'] },
    priority: 'high',
  },
  {
    id: 'itinerary',
    category: 'documents',
    name: { ja: '旅程表', en: 'Itinerary' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'emergency-contacts',
    category: 'documents',
    name: { ja: '緊急連絡先メモ', en: 'Emergency contacts' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'driving-license',
    category: 'documents',
    name: { ja: '運転免許証', en: 'Driving license' },
    conditions: { transport: ['car'] },
    priority: 'critical',
  },
  {
    id: 'international-driving-permit',
    category: 'documents',
    name: { ja: '国際運転免許証', en: 'International driving permit' },
    conditions: { destination: ['international'], transport: ['car'] },
    priority: 'critical',
  },
  {
    id: 'credit-card',
    category: 'documents',
    name: { ja: 'クレジットカード', en: 'Credit card' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'cash',
    category: 'documents',
    name: { ja: '現金', en: 'Cash' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'foreign-currency',
    category: 'documents',
    name: { ja: '外貨', en: 'Foreign currency' },
    conditions: { destination: ['international'] },
    priority: 'high',
  },

  // ─── Clothing ───────────────────────────────────────────────────────────────
  {
    id: 'underwear',
    category: 'clothing',
    name: { ja: '下着（日数分）', en: 'Underwear (per day)' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'extra-underwear',
    category: 'clothing',
    name: { ja: '予備の下着', en: 'Extra underwear' },
    conditions: { minDays: 7 },
    priority: 'medium',
  },
  {
    id: 'socks',
    category: 'clothing',
    name: { ja: '靴下（日数分）', en: 'Socks (per day)' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'tshirts',
    category: 'clothing',
    name: { ja: 'Tシャツ', en: 'T-shirts' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'pants',
    category: 'clothing',
    name: { ja: 'パンツ・ズボン', en: 'Pants / trousers' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'business-suit',
    category: 'clothing',
    name: { ja: 'スーツ', en: 'Business suit' },
    conditions: { tripType: ['business'] },
    priority: 'critical',
  },
  {
    id: 'dress-shirt',
    category: 'clothing',
    name: { ja: 'ワイシャツ', en: 'Dress shirt' },
    conditions: { tripType: ['business'] },
    priority: 'high',
  },
  {
    id: 'tie',
    category: 'clothing',
    name: { ja: 'ネクタイ', en: 'Tie' },
    conditions: { tripType: ['business'] },
    priority: 'medium',
  },
  {
    id: 'swimsuit',
    category: 'clothing',
    name: { ja: '水着', en: 'Swimsuit' },
    conditions: { tripType: ['beach'] },
    priority: 'high',
  },
  {
    id: 'beach-towel',
    category: 'clothing',
    name: { ja: 'ビーチタオル', en: 'Beach towel' },
    conditions: { tripType: ['beach'] },
    priority: 'high',
  },
  {
    id: 'flip-flops',
    category: 'clothing',
    name: { ja: 'ビーチサンダル', en: 'Flip-flops' },
    conditions: { tripType: ['beach'] },
    priority: 'medium',
  },
  {
    id: 'winter-coat',
    category: 'clothing',
    name: { ja: '冬用コート', en: 'Winter coat' },
    conditions: { season: ['winter'] },
    priority: 'high',
  },
  {
    id: 'gloves',
    category: 'clothing',
    name: { ja: '手袋', en: 'Gloves' },
    conditions: { season: ['winter'] },
    priority: 'high',
  },
  {
    id: 'scarf',
    category: 'clothing',
    name: { ja: 'マフラー', en: 'Scarf' },
    conditions: { season: ['winter'] },
    priority: 'medium',
  },
  {
    id: 'beanie',
    category: 'clothing',
    name: { ja: 'ニット帽', en: 'Beanie' },
    conditions: { season: ['winter'] },
    priority: 'medium',
  },
  {
    id: 'light-jacket',
    category: 'clothing',
    name: { ja: '軽いジャケット', en: 'Light jacket' },
    conditions: { season: ['spring', 'fall'] },
    priority: 'medium',
  },
  {
    id: 'rain-jacket',
    category: 'clothing',
    name: { ja: 'レインジャケット', en: 'Rain jacket' },
    conditions: { season: ['spring', 'fall'] },
    priority: 'medium',
  },
  {
    id: 'hat-sun',
    category: 'clothing',
    name: { ja: '帽子（日よけ）', en: 'Sun hat' },
    conditions: { season: ['summer'] },
    priority: 'medium',
  },
  {
    id: 'hiking-boots',
    category: 'clothing',
    name: { ja: 'ハイキングシューズ', en: 'Hiking boots' },
    conditions: { tripType: ['adventure'] },
    priority: 'high',
  },
  {
    id: 'athletic-wear',
    category: 'clothing',
    name: { ja: 'アウトドアウェア', en: 'Athletic / outdoor wear' },
    conditions: { tripType: ['adventure'] },
    priority: 'high',
  },
  {
    id: 'dress-shoes',
    category: 'clothing',
    name: { ja: '革靴', en: 'Dress shoes' },
    conditions: { tripType: ['business'] },
    priority: 'high',
  },
  {
    id: 'pajamas',
    category: 'clothing',
    name: { ja: 'パジャマ', en: 'Pajamas' },
    conditions: {},
    priority: 'medium',
  },

  // ─── Toiletries ─────────────────────────────────────────────────────────────
  {
    id: 'toothbrush',
    category: 'toiletries',
    name: { ja: '歯ブラシ', en: 'Toothbrush' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'toothpaste',
    category: 'toiletries',
    name: { ja: '歯磨き粉', en: 'Toothpaste' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'shampoo',
    category: 'toiletries',
    name: { ja: 'シャンプー', en: 'Shampoo' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'body-wash',
    category: 'toiletries',
    name: { ja: 'ボディソープ', en: 'Body wash' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'deodorant',
    category: 'toiletries',
    name: { ja: 'デオドラント', en: 'Deodorant' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'razor',
    category: 'toiletries',
    name: { ja: 'カミソリ', en: 'Razor' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'sunscreen',
    category: 'toiletries',
    name: { ja: '日焼け止め', en: 'Sunscreen' },
    conditions: { season: ['summer'], tripType: ['beach', 'adventure'] },
    conditionLogic: 'any',
    priority: 'high',
  },
  {
    id: 'sunscreen-winter',
    category: 'toiletries',
    name: { ja: '日焼け止め（高山用）', en: 'Sunscreen (high altitude)' },
    conditions: { tripType: ['adventure'], season: ['winter'] },
    priority: 'medium',
  },
  {
    id: 'moisturizer',
    category: 'toiletries',
    name: { ja: '保湿クリーム', en: 'Moisturizer' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'hair-dryer',
    category: 'toiletries',
    name: { ja: 'ヘアドライヤー', en: 'Hair dryer' },
    conditions: {},
    priority: 'low',
  },
  {
    id: 'comb',
    category: 'toiletries',
    name: { ja: 'くし・ブラシ', en: 'Comb / brush' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'contact-lens',
    category: 'toiletries',
    name: { ja: 'コンタクトレンズ用品', en: 'Contact lens supplies' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'liquids-bag',
    category: 'toiletries',
    name: { ja: '液体物袋（100ml制限）', en: 'Liquids bag (100ml rule)' },
    conditions: { transport: ['plane'] },
    priority: 'high',
  },
  {
    id: 'insect-repellent',
    category: 'toiletries',
    name: { ja: '虫除けスプレー', en: 'Insect repellent' },
    conditions: { tripType: ['adventure'] },
    priority: 'medium',
  },

  // ─── Electronics ────────────────────────────────────────────────────────────
  {
    id: 'phone-charger',
    category: 'electronics',
    name: { ja: 'スマホ充電器', en: 'Phone charger' },
    conditions: {},
    priority: 'critical',
  },
  {
    id: 'phone',
    category: 'electronics',
    name: { ja: 'スマートフォン', en: 'Smartphone' },
    conditions: {},
    priority: 'critical',
  },
  {
    id: 'power-bank',
    category: 'electronics',
    name: { ja: 'モバイルバッテリー', en: 'Power bank' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'laptop',
    category: 'electronics',
    name: { ja: 'ノートPC', en: 'Laptop' },
    conditions: { tripType: ['business'] },
    priority: 'critical',
  },
  {
    id: 'laptop-charger',
    category: 'electronics',
    name: { ja: 'PCアダプター', en: 'Laptop charger' },
    conditions: { tripType: ['business'] },
    priority: 'critical',
  },
  {
    id: 'universal-adapter',
    category: 'electronics',
    name: { ja: '変換プラグ（変圧器）', en: 'Universal power adapter' },
    conditions: { destination: ['international'] },
    priority: 'high',
  },
  {
    id: 'earphones',
    category: 'electronics',
    name: { ja: 'イヤフォン', en: 'Earphones / headphones' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'camera',
    category: 'electronics',
    name: { ja: 'カメラ', en: 'Camera' },
    conditions: { tripType: ['leisure', 'adventure', 'beach'] },
    priority: 'medium',
  },
  {
    id: 'camera-charger',
    category: 'electronics',
    name: { ja: 'カメラ充電器', en: 'Camera charger' },
    conditions: { tripType: ['leisure', 'adventure', 'beach'] },
    priority: 'medium',
  },
  {
    id: 'sim-card',
    category: 'electronics',
    name: { ja: '海外SIM / eSIM', en: 'International SIM / eSIM' },
    conditions: { destination: ['international'] },
    priority: 'high',
  },
  {
    id: 'pocket-wifi',
    category: 'electronics',
    name: { ja: 'ポケットWiFi', en: 'Pocket WiFi' },
    conditions: { destination: ['international'] },
    priority: 'medium',
  },
  {
    id: 'noise-cancelling',
    category: 'electronics',
    name: { ja: 'ノイズキャンセリングイヤフォン', en: 'Noise-cancelling headphones' },
    conditions: { transport: ['plane'] },
    priority: 'medium',
  },
  {
    id: 'e-reader',
    category: 'electronics',
    name: { ja: '電子書籍リーダー', en: 'E-reader' },
    conditions: { minDays: 3 },
    priority: 'low',
  },

  // ─── Health ──────────────────────────────────────────────────────────────────
  {
    id: 'prescription-meds',
    category: 'health',
    name: { ja: '処方薬', en: 'Prescription medications' },
    conditions: {},
    priority: 'critical',
  },
  {
    id: 'painkillers',
    category: 'health',
    name: { ja: '鎮痛剤', en: 'Painkillers' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'cold-medicine',
    category: 'health',
    name: { ja: '風邪薬', en: 'Cold medicine' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'motion-sickness',
    category: 'health',
    name: { ja: '酔い止め', en: 'Motion sickness pills' },
    conditions: { transport: ['plane', 'train'] },
    priority: 'medium',
  },
  {
    id: 'bandages',
    category: 'health',
    name: { ja: '絆創膏', en: 'Bandages' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'first-aid-kit',
    category: 'health',
    name: { ja: '応急処置セット', en: 'First aid kit' },
    conditions: { tripType: ['adventure'] },
    priority: 'high',
  },
  {
    id: 'allergy-meds',
    category: 'health',
    name: { ja: 'アレルギー薬', en: 'Allergy medication' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'stomach-meds',
    category: 'health',
    name: { ja: '胃腸薬', en: 'Stomach medicine' },
    conditions: {},
    priority: 'medium',
  },
  {
    id: 'thermometer',
    category: 'health',
    name: { ja: '体温計', en: 'Thermometer' },
    conditions: { minDays: 5 },
    priority: 'low',
  },
  {
    id: 'hand-sanitizer',
    category: 'health',
    name: { ja: '消毒ジェル', en: 'Hand sanitizer' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'mask',
    category: 'health',
    name: { ja: 'マスク', en: 'Face mask' },
    conditions: {},
    priority: 'high',
  },
  {
    id: 'water-purification',
    category: 'health',
    name: { ja: '浄水タブレット', en: 'Water purification tablets' },
    conditions: { tripType: ['adventure'] },
    priority: 'medium',
  },

  // ─── Entertainment ───────────────────────────────────────────────────────────
  {
    id: 'book',
    category: 'entertainment',
    name: { ja: '本 / 雑誌', en: 'Book / magazine' },
    conditions: {},
    priority: 'low',
  },
  {
    id: 'travel-pillow',
    category: 'entertainment',
    name: { ja: 'トラベルピロー', en: 'Travel pillow' },
    conditions: { transport: ['plane'] },
    priority: 'medium',
  },
  {
    id: 'eye-mask',
    category: 'entertainment',
    name: { ja: 'アイマスク', en: 'Eye mask' },
    conditions: { transport: ['plane'] },
    priority: 'medium',
  },
  {
    id: 'playing-cards',
    category: 'entertainment',
    name: { ja: 'トランプ', en: 'Playing cards' },
    conditions: { tripType: ['leisure', 'adventure'] },
    priority: 'low',
  },
  {
    id: 'snorkeling-gear',
    category: 'entertainment',
    name: { ja: 'シュノーケルセット', en: 'Snorkeling gear' },
    conditions: { tripType: ['beach'] },
    priority: 'medium',
  },
  {
    id: 'guidebook',
    category: 'entertainment',
    name: { ja: 'ガイドブック', en: 'Guidebook' },
    conditions: { tripType: ['leisure', 'adventure'] },
    priority: 'low',
  },
  {
    id: 'translation-app',
    category: 'entertainment',
    name: { ja: '翻訳アプリ確認', en: 'Translation app (check offline mode)' },
    conditions: { destination: ['international'] },
    priority: 'medium',
  },
  {
    id: 'offline-maps',
    category: 'entertainment',
    name: { ja: 'オフラインマップDL', en: 'Offline maps download' },
    conditions: { destination: ['international'] },
    priority: 'high',
  },

  // ─── Misc ────────────────────────────────────────────────────────────────────
  {
    id: 'luggage-lock',
    category: 'misc',
    name: { ja: 'スーツケースロック', en: 'Luggage lock' },
    conditions: { transport: ['plane'] },
    priority: 'medium',
  },
  {
    id: 'luggage-tag',
    category: 'misc',
    name: { ja: '荷物タグ', en: 'Luggage tag' },
    conditions: { transport: ['plane'] },
    priority: 'medium',
  },
  {
    id: 'packing-cubes',
    category: 'misc',
    name: { ja: '圧縮バッグ', en: 'Packing cubes / compression bags' },
    conditions: {},
    priority: 'low',
  },
  {
    id: 'laundry-bag',
    category: 'misc',
    name: { ja: '洗濯袋', en: 'Laundry bag' },
    conditions: { minDays: 7 },
    priority: 'low',
  },
  {
    id: 'detergent-travel',
    category: 'misc',
    name: { ja: '旅行用洗剤', en: 'Travel detergent' },
    conditions: { minDays: 7 },
    priority: 'low',
  },
  {
    id: 'reusable-bag',
    category: 'misc',
    name: { ja: 'エコバッグ', en: 'Reusable shopping bag' },
    conditions: {},
    priority: 'low',
  },
  {
    id: 'umbrella',
    category: 'misc',
    name: { ja: '折り畳み傘', en: 'Compact umbrella' },
    conditions: { season: ['spring', 'fall'] },
    priority: 'medium',
  },
  {
    id: 'sunglasses',
    category: 'misc',
    name: { ja: 'サングラス', en: 'Sunglasses' },
    conditions: { season: ['summer'] },
    priority: 'medium',
  },
  {
    id: 'water-bottle',
    category: 'misc',
    name: { ja: '水筒', en: 'Water bottle' },
    conditions: { tripType: ['adventure'] },
    priority: 'high',
  },
  {
    id: 'snacks',
    category: 'misc',
    name: { ja: '行動食・おやつ', en: 'Snacks' },
    conditions: { tripType: ['adventure'] },
    priority: 'medium',
  },
  {
    id: 'neck-pouch',
    category: 'misc',
    name: { ja: 'セキュリティポーチ', en: 'Security / neck pouch' },
    conditions: { destination: ['international'] },
    priority: 'medium',
  },
  {
    id: 'phrase-book',
    category: 'misc',
    name: { ja: '会話集', en: 'Phrase book' },
    conditions: { destination: ['international'] },
    priority: 'low',
  },
  {
    id: 'travel-adapter-notes',
    category: 'misc',
    name: { ja: 'コンセント形状メモ', en: 'Outlet type note' },
    conditions: { destination: ['international'] },
    priority: 'low',
  },
  {
    id: 'car-snacks',
    category: 'misc',
    name: { ja: '車内用お菓子・飲み物', en: 'Car snacks & drinks' },
    conditions: { transport: ['car'] },
    priority: 'low',
  },
  {
    id: 'car-maps',
    category: 'misc',
    name: { ja: 'カーナビ / 地図確認', en: 'Car navigation / maps' },
    conditions: { transport: ['car'] },
    priority: 'medium',
  },
  {
    id: 'long-trip-entertainment',
    category: 'misc',
    name: { ja: '長旅用エンタメ準備', en: 'Long-trip entertainment prep' },
    conditions: { minDays: 10 },
    priority: 'low',
  },
];
